# Generated by Django 5.2 on 2025-04-26 13:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('PYQ', 'PYQ'), ('AI', 'AI')], default='PYQ', max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('subtopic', models.CharField(blank=True, max_length=100, null=True)),
                ('question_html', ckeditor.fields.RichTextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(max_length=1)),
                ('difficulty_level', models.CharField(blank=True, max_length=50, null=True)),
                ('nature', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation_html', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
