# Generated by Django 5.2 on 2025-04-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.subject'),
        ),
    ]
