# Generated by Django 5.2 on 2025-04-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_sub_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
