# Generated by Django 5.2 on 2025-04-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_rename_subject_question_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='sub_id',
            new_name='subject',
        ),
    ]
