# Generated by Django 5.2 on 2025-07-06 06:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_rename_sub_id_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subtopic',
            new_name='section_name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='topic',
            new_name='topic_name',
        ),
        migrations.AddField(
            model_name='question',
            name='exam_name',
            field=models.CharField(blank=True, default='CSE Prelims', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_generated',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='microtopic_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='q_markdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
