# Generated by Django 5.2 on 2025-07-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_rename_subtopic_question_section_name_and_more'),
        ('syllabus', '0017_alter_section_options_alter_topic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='syllabus.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
