# Generated by Django 5.2 on 2025-07-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_olt_question_olt_type_question_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='check_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('checked', 'Checked')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='q_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
