# Generated by Django 5.2 on 2025-12-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_question_check_status_question_q_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Core', 'Core'), ('Derivative', 'Derivative'), ('Peripheral', 'Peripheral')], db_index=True, max_length=20, null=True),
        ),
    ]
