# Generated by Django 5.2 on 2026-02-05 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_question_category'),
        ('syllabus', '0027_alter_section_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='base_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='question.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='current_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='current_month',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='question',
            name='current_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_class',
            field=models.CharField(choices=[('PYQ', 'PYQ'), ('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C'), ('D', 'Class D'), ('E', 'Class E')], db_index=True, default='PYQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_name',
            field=models.CharField(blank=True, db_index=True, default='CSE Prelims', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_no',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_type',
            field=models.CharField(choices=[('PYQ', 'PYQ'), ('AI', 'AI')], db_index=True, default='PYQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam_name', 'subject', 'is_active'], name='question_qu_exam_na_d6517c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_class', 'is_active'], name='question_qu_questio_d8adf1_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['current_year', 'current_month'], name='question_qu_current_f59c4c_idx'),
        ),
    ]
