# Generated by Django 5.2 on 2026-02-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_question_base_question_question_current_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
