# Generated by Django 5.2 on 2026-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_question_image'),
        ('syllabus', '0027_alter_section_subject'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='question_qu_questio_d8adf1_idx',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_class',
            new_name='q_class',
        ),
        migrations.AddField(
            model_name='question',
            name='current_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_current_related',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['q_class', 'is_active'], name='question_qu_q_class_4dcf72_idx'),
        ),
    ]
