REPLACEMENT_LIST = {
    "M.P.P.C.S.(Pre)":                         "MPPSC",
    "UPSC CSE Prelims":                        "CSE Prelims",
    "UPPCS (Mains)":                           "UPPSC",
    "U.P.P.C.S.(Spl) (Mains)":                 "UPPSC",
    "U.P.P.C.S. (Spl) (Pre)":                  "UPPSC",
    "(U.P.P.C.S. (Mains)":                     "UPPSC",

    "RAS/RTS (Pre)":                           "RPSC",
    "Jharkhand P.C.S.(Pre.)":                  "JPSC",
    "(NULL)":                                  None,
    "Uttarakhand P.C.S. (Mains)":              "UKPSC",
    "U.P. Lower Sub. (Spl) (Pre)":             "UPPSC",
    "Chhattisgarh P.C.S (Pre)":                "CGPSC",
    "63rd B.P.S.C (Pre.)":                     "BPSC",
    "60th to 62nd B.P.S.C.(Pre)":              "BPSC",
    "39th B.P.S.C.(Pre)":                      "BPSC",
    "39th B.P.S.C. (Pre)":                     "BPSC",
    "UP RO/ARO (Pre)":                         "UPPSC",
    "U.P.P.S.C. (GIC)":                        "UPPSC",
    "U.P.P.C.S. (Re. Exam) (Pre)":             "UPPSC",
    "U.P. P.C.S. (Pre)":                       "UPPSC",
    "R.A.S./R.T.S. (Pre).":                    "RPSC",
    "M.P.P.C.S. (Pre)":                        "MPPSC",
    "Chhattisgarh P.C.S, (Pre)":               "CGPSC",
    "60th to 62nd B.P.S.C. (Pre)":             "BPSC",
    "48th to 52nd B.P.S.C. (Pre)":             "BPSC",
    "44th B.P.S.C. (Pre)":                     "BPSC",
    "43rd B.P.S.C. (Pre)":                     "BPSC",
    "40th B.P.S.C. (Pre)":                     "BPSC",
    "Uttarakhand B.C.S. (Pre)":                "UKPSC",
    "UPPCS (Spl) (Pre)":                       "UPPSC",
    "U.P.P.C.S, (Spl) (Mains)":                "UPPSC",
    "U.P. Lower Sub. (Mains)":                 "UPPSC",
    "U.P Lower Sub.(Spl) (Pre)":               "UPPSC",
    "R.A.S. (Pre)":                            "RPSC",
    "Jharkhand PCS (Mains)":                   "JPSC",
    "Jharkhand P.C.S. (Pre.)":                 "JPSC",
    "66th B.P.S.C. Re-Exam (Pre)":             "BPSC",
    "48th to 52nd B.B.S.C. (Pre)":             "BPSC",
    "46th B.P.S.C. (Pre)":                     "BPSC",
    "44th B.P.S.C, (Pre)":                     "BPSC",
    "40th B.P.S.C.(Pre)":                      "BPSC",
    "39th B.B.S.C. (Pre)":                     "BPSC",
    "(R.A.S./R.T.S. (Pre) (Re-Exam)":          "RPSC",
    "(Jharkhand P.C.S. (Pre)":                 "JPSC",
    "(Chhattisgarh P.C.S. (Pre)":              "CGPSC",
    "[M.P.P.C.S. (Pre)":                       "MPPSC",
    "Uttarakhand PCS (Mains)":                 "UKPSC",
    "Uttarakhand P.C.S. (J) (Pre)":            "UKPSC",
    "Uttarakhand P.C.S, (Mains)":              "UKPSC",
    "Uttarakhand Lower Sub.(Pre)":             "UKPSC",
    "Uttarakhand E.C.S. (Pre)":                "UKPSC",
    "URBC.S. (Pre)":                           "UKPSC",
    "UPBEO (Pre)":                             "UPPSC",
    "UP Lower (Pre)":                          "UPPSC",
    "ULB B.C.S, re":                           "UPPSC",
    "U.PP.C.S. (Mains)":                       "UPPSC",
    "U.PP.C.S, (Pre)":                         "UPPSC",
    "U.PBC.S. (Pre)":                          "UPPSC",
    "U.PB.P.C.S. (Mains)":                     "UPPSC",
    "U.P.P.S.C. (R.L)":                        "UPPSC",
    "U.P.P.C.§.(Mains)":                       "UPPSC",
    "U.P.P.C.S. (pl) (Pre)":                   "UPPSC",
    "U.P.P.C.S. (Spl.) (Pre)":                 "UPPSC",
    "U.P.P.C.S. (Spl)(Mains)":                 "UPPSC",
    "U.P.P.C.S. (Sp":                          "UPPSC",
    "U.P.P,.C.S. (Mains)":                     "UPPSC",
    "U.P.BC.S. (Spi) (Mains)":                 "UPPSC",
    "U.P.BC.S. (Pre)":                         "UPPSC",
    "U.P.B.C.S.(Pre)":                         "UPPSC",
    "U.P.B.C.S. (Re. Exam)(Pre)":              "UPPSC",
    "U.P. P.C.S, (Pre)":                       "UPPSC",
    "U.P. Lower Spl. (Pre)":                   "UPPSC",
    "U.P. B.C.S. (Mains)":                     "UPPSC",
    "U.P P.C.S.(Mains)":                       "UPPSC",
    "U.P BCS, (Pre)":                          "UPPSC",
    "U.BB.C.S. (Pre":                          "UPPSC",
    "U.B.P.C.S. (Re. Exam) (Pre)":             "UPPSC",
    "RA.S./R.T.S.(Pre)":                       "RPSC",
    "R.AS./R.T.S.(Pre)":                       "RPSC",
    "R.A.S/RUES. (Re. Exain)(Pre)":            "RPSC",
    "R.A.S./R.TS.(Pre)":                       "RPSC",
    "R.A.S./R.T.S. (Pre) (Re-Exam)":           "RPSC",
    "R.A.S./R.T.S, (Pre)":                     "RPSC",
    "R.A.S./R.T.S(Pre)":                       "RPSC",
    "R.A.S./R.I.S. (Re. Exam) (Pre)":          "RPSC",
    "R.A.S./R.E.S. (Pre)":                     "RPSC",
    "R.A.S./R.E.S (Pre)":                      "RPSC",
    "R.A.S./B.T.S. (Pre)":                     "RPSC",
    "R.A.S./ R.TS, (Pre)":                     "RPSC",
    "MLP.B.C.S, (Pre)":                        "MPPSC",
    "M.P.P.S.C. (Pre)":                        "MPPSC",
    "Jharkhand P.C.S (Pre)":                   "JPSC",
    "Chhattisgarh PCS (Pre":                   "CGPSC",
    "CDS(1)":                                  "CDS",
    "CDS  (ID":                                "CDS",
    "CDS  (11":                                "CDS",
    "6Sth B.P.S.C. (Pre)":                     "BPSC",
    "67th BPSC (Pre) (Re-Fxam)":               "BPSC",
    "67th BPSC (Pre)":                         "BPSC",
    "67th B.P.S.C.(Pre) (Re-Exam)":            "BPSC",
    "67th B.P.S.C. (Pre)":                     "BPSC",
    "67 BPSC (Pre) (Re-Exam)":                 "BPSC",
    "66th B.PS.C (Pre)":                       "BPSC",
    "66th B.P.S.C. (Pre.)":                    "BPSC",
    "66th B.P.S.C. (Pre)":                     "BPSC",
    "66th B.P.S.C, (Pre)":                     "BPSC",
    "65th B.P.S.C. (Pre)":                     "BPSC",
    "64th BPSC (Pre)":                         "BPSC",
    "64th B.P.S.C (Pre)":                      "BPSC",
    "64 BPSC (Pre)":                           "BPSC",
    "63rd B.P.S.C. (Pre.)":                    "BPSC",
    "63rd B.P.8.C (Pre.)":                     "BPSC",
    "60th to 62nd B.P.P.S.C.(Pre)":            "BPSC",
    "56th to 59th B.P.S.C.(Pre)":              "BPSC",
    "56th to 59th B.P.S.C. (Pre)":             "BPSC",
    "56th to 59th B.B.S.C. (Pre)":             "BPSC",
    "53rd to 5Sth B.P.S.C. (Pre)":             "BPSC",
    "53rd to 55th B.P.S.C.(Pre)":              "BPSC",
    "53rd to 55th B.P.S.C. (Pre)":             "BPSC",
    "53d to 55th B.P.S.C. (Pre)":              "BPSC",
    "4ist B.B.S.C.(Pre)":                      "BPSC",
    "49th B.P.S.C (Pre)":                      "BPSC",
    "48th to 52nd B.PS.C.(Pre)":               "BPSC",
    "48th to 52nd B.PS.C. (Pre)":              "BPSC",
    "47th B.PS.C. (Pre)":                      "BPSC",
    "47th B.P.S.C.(Pre)":                      "BPSC",
    "47th B.P.S.C. (Pre)":                     "BPSC",
    "47th B.B.S.C.(Pre)":                      "BPSC",
    "46th B.PS.C, (Pre)":                      "BPSC",
    "46th B.P.S.C.(Pre)":                      "BPSC",
    "45th B.P.S.C (Pre)":                      "BPSC",
    "45th B.B.S.C.(Pre)":                      "BPSC",
    "44th B.P.S.C.(Pre)":                      "BPSC",
    "43th to 52nd B.P.S.C. (Pre)":             "BPSC",
    "43rd B.P.S.C.(Pre)":                      "BPSC",
    "43rd B.P.S.C, (Pre)":                     "BPSC",
    "42nd B.PS.C. (Pre)":                      "BPSC",
    "42nd B.P.S.C. (Pre)":                     "BPSC",
    "42nd B.B.S.C, (Pre)":                     "BPSC",
    "41st B.P.S.C.(Pre)":                      "BPSC",
    "41st B.P.S.C. (Pre)":                     "BPSC",
    "41st B.B.S.C.(Pre)":                      "BPSC",
    "41st B.B.S.C. (Pre)":                     "BPSC",
    "40th B.P.S.C, (Pre)":                     "BPSC",
    "40th B.B.S.C. (Pre)":                     "BPSC",
    "(U.PIPC.S. (Pre)":                        "UPPSC",
    "(R.A.S./R.T.S.(Pre)":                     "RPSC",
    "(R.A.S./R.T.S. (Pre)":                    "RPSC",
    "(M.P.P.C.S, (Pre)":                       "MPPSC",
    "(CLBEC.S. (Pre)":                         "BPSC",
}