# Generated by Django 5.2 on 2025-06-16 15:36

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microtopic',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.CharField(max_length=10)),
                ('q_statement', ckeditor.fields.RichTextField()),
                ('a', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
                ('d', models.TextField()),
                ('correct_option', models.CharField(max_length=1)),
                ('explanation', ckeditor.fields.RichTextField()),
                ('exam', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('is_check', models.BooleanField(default=False)),
                ('microtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.microtopic')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.topic')),
            ],
        ),
    ]
