# Generated by Django 5.2 on 2025-06-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_alter_microtopic_options_alter_subtopic_options_ques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='subject',
        ),
    ]
