# Generated by Django 5.2 on 2025-06-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_remove_ques_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.subject'),
        ),
        migrations.AddField(
            model_name='ques',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
