# Generated by Django 5.2 on 2025-06-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_ques_subject_ques_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
