# Generated by Django 5.2 on 2025-06-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_ques_added_at_ques_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ques',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
