# Generated by Django 5.2 on 2025-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_alter_ques_added_at_alter_ques_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='for_review',
            field=models.BooleanField(default=False),
        ),
    ]
