# Generated by Django 5.2 on 2025-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_ques_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='microtopic_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='subtopic_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='topic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
