# Generated by Django 5.2 on 2025-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_ques_microtopic_name_ques_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
