# Generated by Django 5.2 on 2025-06-28 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_ques_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='exp_generated',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ques',
            name='q_markdown',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
