# Generated by Django 5.2 on 2025-06-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_ques_exp_generated_ques_q_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='OLT',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
