# Generated by Django 5.2 on 2025-06-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0012_ques_olt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ques',
            old_name='OLT',
            new_name='olt_type',
        ),
    ]
