# Generated by Django 5.2 on 2025-06-29 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0013_rename_olt_ques_olt_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='subject',
            new_name='section',
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('section', 'name')},
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='syllabus.subject')),
            ],
            options={
                'unique_together': {('subject', 'name')},
            },
        ),
    ]
