# Generated by Django 5.2 on 2025-06-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0014_rename_subject_topic_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.section'),
        ),
    ]
