# Generated by Django 5.2 on 2025-06-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0015_alter_topic_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.section'),
        ),
    ]
