# Generated by Django 5.2 on 2025-07-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0016_ques_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id']},
        ),
    ]
