# Generated by Django 5.2 on 2025-07-16 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0017_alter_section_options_alter_topic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
