# Generated by Django 5.2 on 2025-07-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_question_check_status_question_q_no'),
        ('syllabus', '0018_alter_ques_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='olt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ques_set', to='question.olt'),
        ),
    ]
