# Generated by Django 5.2 on 2025-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0019_ques_olt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='asked_band',
            field=models.CharField(choices=[('most', 'Most Asked'), ('asked', 'Asked'), ('rare', 'Rarely Asked'), ('never', 'Never Asked')], db_index=True, default='never', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='weightage',
            field=models.FloatField(default=0),
        ),
    ]
