# Generated by Django 5.2 on 2025-10-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0020_topic_asked_band_topic_weightage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='asked_band',
            new_name='tier',
        ),
    ]
