# Generated by Django 5.2 on 2025-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0021_rename_asked_band_topic_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tier',
            field=models.CharField(choices=[('most', 'Most Asked'), ('general', 'Generally Asked'), ('rare', 'Rarely Asked'), ('never', 'Never Asked')], db_index=True, default='never', max_length=10),
        ),
    ]
