# Generated by Django 5.2 on 2025-11-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0022_alter_topic_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='UPSC CSE (Prelims)', max_length=200)),
                ('demand_insights', models.TextField()),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('pyq_count', models.PositiveIntegerField(default=0)),
                ('year_span', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_demands', to='syllabus.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_demands', to='syllabus.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_demands', to='syllabus.topic')),
            ],
            options={
                'unique_together': {('topic', 'exam_name')},
            },
        ),
    ]
