# Generated by Django 5.2 on 2025-12-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0023_topicdemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
