# Generated by Django 5.2 on 2026-01-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0024_topic_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='tier',
            field=models.CharField(choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], db_index=True, default='tier3', max_length=10),
        ),
    ]
