# Generated by Django 5.2 on 2026-01-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0025_alter_topic_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopicCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('demand', models.TextField(blank=True, null=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('question_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_candidates', to='syllabus.topic')),
            ],
            options={
                'ordering': ['topic', 'sequence_number', 'id'],
                'unique_together': {('topic', 'name'), ('topic', 'sequence_number')},
            },
        ),
    ]
