# Generated by Django 5.2 on 2026-02-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0026_subtopiccandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='syllabus.subject'),
        ),
    ]
