# Generated by Django 5.2 on 2025-10-08 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('syllabus', '0020_topic_asked_band_topic_weightage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmi', models.FloatField(blank=True, db_index=True, null=True)),
                ('tmi', models.FloatField(blank=True, db_index=True, null=True)),
                ('cmi', models.FloatField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statuses', to='syllabus.exam')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_statuses', to='syllabus.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statuses', to='syllabus.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statuses', to='syllabus.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'exam', 'subject'], name='analysis_to_user_id_d6ff1c_idx'), models.Index(fields=['user', 'subject', 'section'], name='analysis_to_user_id_9701b9_idx'), models.Index(fields=['user', 'pmi'], name='analysis_to_user_id_796416_idx'), models.Index(fields=['topic'], name='analysis_to_topic_i_217fe2_idx')],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
