# Generated by Django 5.2 on 2025-10-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_topicstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicstatus',
            name='rounds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
