# Generated by Django 5.2 on 2025-12-07 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_topicstatus_rounds'),
        ('syllabus', '0024_topic_total_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topicstatus',
            name='analysis_to_user_id_d6ff1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='topicstatus',
            name='analysis_to_user_id_9701b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='topicstatus',
            name='analysis_to_user_id_796416_idx',
        ),
        migrations.RemoveIndex(
            model_name='topicstatus',
            name='analysis_to_topic_i_217fe2_idx',
        ),
        migrations.RenameField(
            model_name='topicstatus',
            old_name='rounds',
            new_name='practice_rounds',
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='band',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='bucket',
            field=models.CharField(blank=True, choices=[('weak', 'Weak'), ('transition', 'Transition'), ('strong', 'Strong')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='test_questions_attempted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='topicstatus',
            index=models.Index(fields=['user', 'subject'], name='analysis_to_user_id_8fc0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='topicstatus',
            index=models.Index(fields=['user', 'bucket'], name='analysis_to_user_id_a9e894_idx'),
        ),
        migrations.AddIndex(
            model_name='topicstatus',
            index=models.Index(fields=['user', 'band'], name='analysis_to_user_id_fec136_idx'),
        ),
    ]
