# Generated by Django 5.2 on 2026-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_topicstatus_analysis_to_user_id_d6ff1c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicstatus',
            name='pctwrong_practice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='pctwrong_test',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
