# Generated by Django 5.2 on 2026-01-04 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_topicstatus_pctwrong_practice_and_more'),
        ('syllabus', '0025_alter_topic_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topicstatus',
            name='analysis_to_user_id_a9e894_idx',
        ),
        migrations.RenameField(
            model_name='topicstatus',
            old_name='bucket',
            new_name='bucket_by_mastery',
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='bucket_by_pct',
            field=models.CharField(blank=True, choices=[('weak', 'Weak'), ('transition', 'Transition'), ('strong', 'Strong')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='tci',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='topicstatus',
            name='test_questions_seen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='topicstatus',
            index=models.Index(fields=['user', 'bucket_by_mastery'], name='analysis_to_user_id_ed6a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='topicstatus',
            index=models.Index(fields=['user', 'bucket_by_pct'], name='analysis_to_user_id_acf3ee_idx'),
        ),
    ]
