# Generated by Django 5.2 on 2026-01-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_remove_topicstatus_analysis_to_user_id_a9e894_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topicstatus',
            name='analysis_to_user_id_fec136_idx',
        ),
        migrations.RemoveIndex(
            model_name='topicstatus',
            name='analysis_to_user_id_ed6a4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='topicstatus',
            name='analysis_to_user_id_acf3ee_idx',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='band',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='bucket_by_mastery',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='bucket_by_pct',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='cmi',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='pctwrong_practice',
        ),
        migrations.RemoveField(
            model_name='topicstatus',
            name='pctwrong_test',
        ),
    ]
