# Generated by Django 5.2 on 2025-07-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practicesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='applied_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='applied_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='blind_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='blind_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='guesswork_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='guesswork_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='sureshot_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='sureshot_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
