# Generated by Django 5.2 on 2025-10-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_practicesession_applied_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='blind_attempts',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='blind_wrong',
        ),
        migrations.RemoveField(
            model_name='practicesession',
            name='unattempted',
        ),
    ]
