# Generated by Django 5.2 on 2025-10-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_remove_practicesession_blind_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='unattempted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
