# Generated by Django 5.2 on 2025-12-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_practicesession_unattempted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='unattempted',
        ),
    ]
