# Generated by Django 5.2 on 2025-04-27 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0005_rename_sub_id_question_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('test_type', models.CharField(blank=True, choices=[('full_length', 'Full-Length Test'), ('sectional', 'Sectional Test'), ('micro', 'Micro Test')], max_length=50, null=True)),
                ('exam', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('unattempted', models.PositiveIntegerField(default=0)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sureshot_attempts', models.PositiveIntegerField(default=0)),
                ('applied_attempts', models.PositiveIntegerField(default=0)),
                ('guesswork_attempts', models.PositiveIntegerField(default=0)),
                ('sureshot_wrong', models.PositiveIntegerField(default=0)),
                ('applied_wrong', models.PositiveIntegerField(default=0)),
                ('guesswork_wrong', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAttemptSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('wrong_attempts', models.PositiveIntegerField(default=0)),
                ('sureshot_attempts', models.PositiveIntegerField(default=0)),
                ('applied_attempts', models.PositiveIntegerField(default=0)),
                ('guesswork_attempts', models.PositiveIntegerField(default=0)),
                ('blind_attempts', models.PositiveIntegerField(default=0)),
                ('sureshot_wrong', models.PositiveIntegerField(default=0)),
                ('applied_wrong', models.PositiveIntegerField(default=0)),
                ('guesswork_wrong', models.PositiveIntegerField(default=0)),
                ('net_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'question'],
                'indexes': [models.Index(fields=['user', 'question'], name='tests_quest_user_id_87fd81_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_summary')],
            },
        ),
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(blank=True, null=True)),
                ('user_answered', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('attempt_type', models.CharField(blank=True, choices=[('sureshot', 'Sureshot'), ('applied', 'Applied'), ('guesswork', 'Guesswork'), ('blind', 'Blind Attempt')], max_length=10, null=True)),
                ('attempt_result', models.CharField(blank=True, choices=[('right', 'Right'), ('wrong', 'Wrong')], max_length=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['user', 'question'], name='tests_quest_user_id_262908_idx'), models.Index(fields=['test', 'serial'], name='tests_quest_test_id_d9a102_idx')],
            },
        ),
    ]
