# Generated by Django 5.2 on 2025-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattemptsummary',
            name='blind_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionlog',
            name='attempt_type',
            field=models.CharField(blank=True, choices=[('sureshot', 'Sureshot'), ('applied', 'Applied'), ('guesswork', 'Guesswork'), ('blind', 'Blind Attempt'), ('unattempted', 'Unattempted')], default='unattempted', max_length=11),
        ),
    ]
