# Generated by Django 5.2 on 2025-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_questionattemptsummary_blind_wrong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='blind_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
