# Generated by Django 5.2 on 2025-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_blind_wrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlog',
            name='user_answered',
            field=models.CharField(blank=True, choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, null=True),
        ),
    ]
