# Generated by Django 5.2 on 2025-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_questionlog_user_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
