# Generated by Django 5.2 on 2025-04-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_test_attempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='attempt',
            new_name='attempt_serial',
        ),
    ]
