# Generated by Django 5.2 on 2025-05-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0006_rename_attempt_test_attempt_serial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="blind_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
