# Generated by Django 5.2 on 2025-06-11 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_rename_sub_id_question_subject'),
        ('tests', '0007_test_blind_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questionlog',
            index=models.Index(fields=['user', 'attempt_result'], name='tests_quest_user_id_f39954_idx'),
        ),
    ]
