# Generated by Django 5.2 on 2025-07-10 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        ('tests', '0008_questionlog_tests_quest_user_id_f39954_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='practiceSession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.practicesession'),
        ),
    ]
