# Generated by Django 5.2 on 2025-07-10 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0017_alter_section_options_alter_topic_options'),
        ('tests', '0009_questionlog_practicesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAttemptSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('test', 'Test')], max_length=8)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('wrong_attempts', models.PositiveIntegerField(default=0)),
                ('sureshot_attempts', models.PositiveIntegerField(default=0)),
                ('applied_attempts', models.PositiveIntegerField(default=0)),
                ('guesswork_attempts', models.PositiveIntegerField(default=0)),
                ('blind_attempts', models.PositiveIntegerField(default=0)),
                ('sureshot_wrong', models.PositiveIntegerField(default=0)),
                ('applied_wrong', models.PositiveIntegerField(default=0)),
                ('guesswork_wrong', models.PositiveIntegerField(default=0)),
                ('blind_wrong', models.PositiveIntegerField(default=0)),
                ('net_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'topic', 'mode'],
                'indexes': [models.Index(fields=['user', 'topic', 'mode'], name='tests_topic_user_id_b2dbf0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'topic', 'mode'), name='unique_user_topic_mode_summary')],
            },
        ),
    ]
