# Generated by Django 5.2 on 2025-07-11 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_practicesession_applied_attempts_and_more'),
        ('question', '0009_question_check_status_question_q_no'),
        ('tests', '0010_topicattemptsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questionlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('practiceSession__isnull', True), ('test__isnull', False)), models.Q(('practiceSession__isnull', False), ('test__isnull', True)), _connector='OR'), name='only_one_mode_active'),
        ),
    ]
