# Generated by Django 5.2 on 2025-07-31 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0019_ques_olt'),
        ('tests', '0011_questionlog_only_one_mode_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='sub_topic',
        ),
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='test',
            name='topic',
        ),
        migrations.AddField(
            model_name='questionattemptsummary',
            name='last_attempted',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='questionattemptsummary',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='questionlog',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.topic'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topicattemptsummary',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='topicattemptsummary',
            name='mastery_index',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='questionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='TestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_olt_filters', models.BooleanField(default=False)),
                ('no_of_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.exam')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('section__isnull', True), ('subject__isnull', True)), fields=('user', 'exam', 'year'), name='uniq_exam_year_template_per_user')],
            },
        ),
    ]
