# Generated by Django 5.2 on 2025-07-31 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_practicesession_applied_attempts_and_more'),
        ('question', '0009_question_check_status_question_q_no'),
        ('syllabus', '0019_ques_olt'),
        ('tests', '0012_remove_test_sub_topic_remove_test_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='test',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='test',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.testtemplate'),
        ),
        migrations.AddField(
            model_name='test',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='test',
            name='attempt_serial',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='questionlog',
            constraint=models.UniqueConstraint(fields=('test', 'question'), name='unique_question_per_test'),
        ),
    ]
