# Generated by Django 5.2 on 2025-07-31 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('practice', '0003_practicesession_applied_attempts_and_more'),
        ('question', '0009_question_check_status_question_q_no'),
        ('syllabus', '0019_ques_olt'),
        ('tests', '0013_remove_test_is_completed_test_score_test_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionlog',
            options={'ordering': ['serial', 'timestamp']},
        ),
        migrations.RenameIndex(
            model_name='questionlog',
            new_name='ql_test_serial_idx',
            old_name='tests_quest_test_id_d9a102_idx',
        ),
        migrations.RenameIndex(
            model_name='questionlog',
            new_name='ql_user_question_idx',
            old_name='tests_quest_user_id_262908_idx',
        ),
        migrations.RenameIndex(
            model_name='questionlog',
            new_name='ql_user_attempt_result_idx',
            old_name='tests_quest_user_id_f39954_idx',
        ),
        migrations.AddField(
            model_name='questionlog',
            name='error_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionlog',
            name='self_error',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_logs', to='analysis.errortype'),
        ),
        migrations.AddIndex(
            model_name='questionlog',
            index=models.Index(fields=['practiceSession', 'serial'], name='ql_practice_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlog',
            index=models.Index(fields=['user', 'test', 'serial'], name='ql_user_test_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlog',
            index=models.Index(fields=['user', 'practiceSession', 'serial'], name='ql_user_practice_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlog',
            index=models.Index(fields=['user', 'self_error'], name='ql_user_selferror_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlog',
            index=models.Index(fields=['user', 'topic'], name='ql_user_topic_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionlog',
            constraint=models.UniqueConstraint(fields=('test', 'serial'), name='unique_serial_per_test'),
        ),
        migrations.AddConstraint(
            model_name='questionlog',
            constraint=models.UniqueConstraint(fields=('practiceSession', 'question'), name='unique_question_per_practice'),
        ),
        migrations.AddConstraint(
            model_name='questionlog',
            constraint=models.UniqueConstraint(fields=('practiceSession', 'serial'), name='unique_serial_per_practice'),
        ),
    ]
