# Generated by Django 5.2 on 2025-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_alter_questionlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questionlog',
            name='ql_test_serial_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionlog',
            name='ql_user_attempt_result_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionlog',
            name='ql_practice_serial_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionlog',
            name='ql_user_test_serial_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionlog',
            name='ql_user_practice_serial_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionlog',
            name='ql_user_selferror_idx',
        ),
        migrations.RemoveField(
            model_name='questionattemptsummary',
            name='blind_attempts',
        ),
        migrations.RemoveField(
            model_name='questionattemptsummary',
            name='blind_wrong',
        ),
        migrations.RemoveField(
            model_name='questionlog',
            name='error_note',
        ),
        migrations.RemoveField(
            model_name='questionlog',
            name='self_error',
        ),
        migrations.RemoveField(
            model_name='topicattemptsummary',
            name='mastery_index',
        ),
        migrations.AlterField(
            model_name='test',
            name='attempt_serial',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
