# Generated by Django 5.2 on 2025-12-07 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_question_check_status_question_q_no'),
        ('syllabus', '0024_topic_total_questions'),
        ('tests', '0015_remove_questionlog_ql_test_serial_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicOLTSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('test', 'Test')], max_length=10)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('wrong_attempts', models.PositiveIntegerField(default=0)),
                ('sureshot_attempts', models.PositiveIntegerField(default=0)),
                ('applied_attempts', models.PositiveIntegerField(default=0)),
                ('guesswork_attempts', models.PositiveIntegerField(default=0)),
                ('sureshot_wrong', models.PositiveIntegerField(default=0)),
                ('applied_wrong', models.PositiveIntegerField(default=0)),
                ('guesswork_wrong', models.PositiveIntegerField(default=0)),
                ('net_marks', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.olt')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'topic', 'mode'], name='tests_topic_user_id_d9d97e_idx'), models.Index(fields=['user', 'olt', 'mode'], name='tests_topic_user_id_aea628_idx')],
                'unique_together': {('user', 'topic', 'olt', 'mode')},
            },
        ),
    ]
