# Generated by Django 5.2 on 2026-01-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_topicoltsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicattemptsummary',
            name='total_test_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
