# Generated by Django 5.2 on 2026-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_topicattemptsummary_total_test_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicattemptsummary',
            name='last_n_questions_test',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='topicattemptsummary',
            name='test_questions_seen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
