# Generated by Django 5.2 on 2026-01-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_topicattemptsummary_last_n_questions_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicattemptsummary',
            name='test_questions_seen',
        ),
    ]
