# Generated by Django 5.2 on 2025-08-05 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_exam_profile_exam_date_profile_is_onboarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='profile',
            name='days_active',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='exam_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_attempt_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_streak_credit_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pledge',
            field=models.TextField(blank=True, help_text='User-written pledge captured during onboarding.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_questions_target',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='why_exam',
            field=models.TextField(blank=True, help_text='Personal reason or motivation statement.', verbose_name='Why are you preparing?'),
        ),
    ]
