# Generated by Django 5.2 on 2025-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_date_joined_profile_days_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_seen_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
