# Generated by Django 5.2 on 2025-08-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_date_joined_alter_profile_last_seen_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='days_active',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
