# Generated by Django 5.2 on 2025-12-04 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_days_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('bonus', 'Bonus'), ('pro', 'Pro')], max_length=20)),
                ('total_attempts_limit', models.PositiveIntegerField(blank=True, help_text='None = unlimited total attempts.', null=True)),
                ('daily_attempts_limit', models.PositiveIntegerField(blank=True, help_text='None = no daily cap.', null=True)),
                ('total_attempts_used', models.PositiveIntegerField(default=0)),
                ('daily_attempts_used', models.PositiveIntegerField(default=0)),
                ('last_attempt_day', models.DateField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('expiry_datetime', models.DateTimeField(blank=True, help_text='Only relevant for PRO; Basic/Bonus usually keep this null.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['user', 'plan'], name='user_subscr_user_id_aa712f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('sureshot_attempts', models.PositiveIntegerField(default=0)),
                ('applied_attempts', models.PositiveIntegerField(default=0)),
                ('guess_attempts', models.PositiveIntegerField(default=0)),
                ('sureshot_wrong', models.PositiveIntegerField(default=0)),
                ('applied_wrong', models.PositiveIntegerField(default=0)),
                ('guess_wrong', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='user_userda_user_id_e493d9_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
