# Generated by Django 5.2 on 2025-12-07 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_subscription_userdailystats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='daily_attempts_used',
            new_name='daily_attempts_booked',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='total_attempts_used',
            new_name='total_attempts_booked',
        ),
        migrations.AddField(
            model_name='profile',
            name='days_since_active',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='days_since_joined',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_paid_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.subscription'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_practice_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_test_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailystats',
            name='practice_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userdailystats',
            name='test_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userdailystats',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailystats',
            name='total_correct',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailystats',
            name='total_wrong',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'start_datetime'], name='user_subscr_user_id_cf4ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'expiry_datetime'], name='user_subscr_user_id_4ebc7e_idx'),
        ),
        migrations.AddField(
            model_name='userprobill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
