# Generated by Django 5.2 on 2025-12-07 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprobill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('bonus', 'Bonus'), ('pro', 'Pro')], help_text='Plan that this payment is intended to activate or extend.', max_length=20)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Number of days of PRO access this payment corresponds to (if applicable).', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='ISO currency code, e.g., INR, USD.', max_length=10)),
                ('provider', models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('other', 'Other / Manual')], default='razorpay', max_length=20)),
                ('provider_order_id', models.CharField(blank=True, help_text='Order ID from the payment gateway.', max_length=100, null=True)),
                ('provider_payment_id', models.CharField(blank=True, help_text='Payment ID from the payment gateway.', max_length=100, null=True)),
                ('provider_signature', models.CharField(blank=True, help_text='Signature / HMAC sent by payment gateway for verification.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='initiated', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when payment moves to SUCCESS / FAILED / REFUNDED.', null=True)),
                ('meta', models.JSONField(blank=True, help_text='Optional extra data from gateway or internal notes.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserProBill',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='user_paymen_user_id_a4ce9c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_order_id'], name='user_paymen_provide_ccbe52_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='user_paymen_provide_f3730b_idx'),
        ),
    ]
