# Generated by Django 5.2 on 2025-12-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_payment_delete_userprobill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdailystats',
            old_name='guess_attempts',
            new_name='guesswork_attempts',
        ),
        migrations.RenameField(
            model_name='userdailystats',
            old_name='guess_wrong',
            new_name='guesswork_wrong',
        ),
    ]
