# Generated by Django 5.2 on 2026-01-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_guess_attempts_userdailystats_guesswork_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topicstatus_method',
            field=models.CharField(choices=[('MAS', 'Mastery indices'), ('PCT', 'Percentage wrong')], db_index=True, default='PCT', max_length=3),
        ),
    ]
