# Generated by Django 5.2 on 2026-01-11 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_topicstatus_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailystats',
            name='practice_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdailystats',
            name='test_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserOverallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.JSONField(default=dict)),
                ('total_correct', models.JSONField(default=dict)),
                ('total_wrong', models.JSONField(default=dict)),
                ('sureshot_attempts', models.JSONField(default=dict)),
                ('applied_attempts', models.JSONField(default=dict)),
                ('guesswork_attempts', models.JSONField(default=dict)),
                ('sureshot_wrong', models.JSONField(default=dict)),
                ('applied_wrong', models.JSONField(default=dict)),
                ('guesswork_wrong', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
